# App-specific styling
export NVIM_GTK_NO_HEADERBAR=1
export NVIM_GTK_PREFER_DARK_THEME=1
export NVIM_GTK_NO_WINDOW_DECORATION=1
export _JAVA_AWT_WM_NONREPARENTING=1

# Enable Wayland
export QT_QPA_PLATFORM=wayland-egl
export QUTE_SKIP_WAYLAND_CHECK=1
export MOZ_ENABLE_WAYLAND=1
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1

export GOPATH=$HOME/go
export EDITOR="nvim"

export PATH=$PATH:$HOME/.local/bin:$HOME/go/bin

# Opt-out
export DOTNET_CLI_TELEMETRY_OPTOUT=1

export _JAVA_OPTIONS='-Djdk.gtk.version=2'

# IME
GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx
