PROMPT="%n@%M:%~ $ "
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

bindkey -v
zstyle :compinstall filename '/home/adem/.zshrc'
autoload -Uz compinit
compinit

alias ll="ls -la --color"
alias vim=nvim

# auto-start sway when in tty1
if [ "$(tty)" = "/dev/tty1" ]; then
    sway
    exit 0
fi
